Team32_October/src/authApp/urls.py
from django.urls import include, path
from . import views
from django.urls import path, include 

app_name = 'authApp'
urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('', views.landing_page, name='landing_page'),
    path('logout/', views.logout, name='logout'),
    path('ajax_generate_code/', views.ajax_generate_code, name='ajax_generate_code'),
    path("file/", include("fileupload.urls")),
    path('payment/paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('payment/', views.payment, name='payment'),
    path('doctorregistration/', views.doctorregister, name='doctorregistration'),
    path('doctorlogin/', views.doctorlogin, name='doctorlogin'),
    path('doctorlogout/', views.doctorlogout, name='doctorlogout'),
    path('doctorhomepage/', views.doctorhome, name='doctorhomepage'),
    path('waiting/', views.waiting, name='waiting'),
    path('ajax_doctor_code/', views.ajax_doctor_code, name='ajax_doctor_code'),
    path('ajax_org_code/', views.ajax_org_code, name='ajax_organization_code'),
    path('organizationregister/', views.organization_register, name='organizationregister'),
    path('organizationlogin/', views.organization_login, name='organizationlogin'),
    path('organizationlogout/', views.organization_logout, name='organizationlogout'),
    path('organizationhome/', views.organization_home, name='organizationhome'),

]

Team32_October/src/myapp/urls.py
from django.urls import path
from .views import my_view, docsls

urlpatterns = [
    path('', my_view, name='my-view'),
    path('docsls/', docsls, name='docsls'),
]

Team32_October/src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('homepage/', include('authApp.urls')),
    path("admin/", admin.site.urls),
    path("", include("authApp.urls")),
    path("file/", include("fileupload.urls")),
    path("myapp/", include("myapp.urls")),
]

Team32_October/src/authApp/models.py
from django.db import models

departments=[('Cardiologist','Cardiologist'),
('Dermatologists','Dermatologists'),
('Emergency Medicine Specialists','Emergency Medicine Specialists'),
('Allergists/Immunologists','Allergists/Immunologists'),
('Surgeon','Surgeon'),
]

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=500, unique=True)
    username = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    blood = models.CharField(max_length=4)

class Transaction(models.Model):
    made_by = models.ForeignKey(User, related_name='transactions', on_delete=models.CASCADE)
    made_on = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField()
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True)
    checksum = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.order_id is None and self.made_on and self.id:
            self.order_id = self.made_on.strftime('PAY2ME%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

#create doctor model
class Doctor(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=500, unique=True)
    username = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    department = models.CharField(max_length=255, choices=departments)
    is_logged_in = models.BooleanField(default = False)

#create organization model
class Organization(models.Model):
    name = models.CharField(max_length=255)
    Organization_Type = models.CharField(max_length=255)
    email = models.EmailField(max_length=500, unique=True)
    username = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    is_logged_in = models.BooleanField(default = False)

Team32_October/src/authApp/forms.py
from django import forms
from .models import User
from .models import Doctor
from .models import Organization

"""hide password field in login form"""
passwordInputWidget = {
 'password': forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'})),
}
class RegisterForm(forms.ModelForm):
 class Meta:
  model = User
  fields = '__all__'
  widgets = [passwordInputWidget]
  widgets = {
    'username': forms.TextInput(attrs={'class': 'form-control'}),
    'email': forms.EmailInput(attrs={'class': 'form-control'}),
    'password': forms.PasswordInput(attrs={'class': 'form-control'}),
    'first_name': forms.TextInput(attrs={'class': 'form-control'}),
    'last_name': forms.TextInput(attrs={'class': 'form-control'}),
    'phone': forms.TextInput(attrs={'class': 'form-control'}),
    'blood_group': forms.TextInput(attrs={'class': 'form-control'}),
  }

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

class LoginForm(forms.ModelForm):
 class Meta:
  model = User
  fields = ['username', 'password']
  widgets = [passwordInputWidget]
  widgets = {
    'password': forms.PasswordInput(attrs={'class': 'form-control'}),
  }

#create class for doctor
class DoctorRegisterForm(forms.ModelForm):
  class Meta:
    model = Doctor
    fields = ['name', 'email','username', 'password', 'department']
    widgets = [passwordInputWidget]
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'}),
      'username': forms.TextInput(attrs={'class': 'form-control'}),
      'password': forms.PasswordInput(attrs={'class': 'form-control'}),
      'department': forms.TextInput(attrs={'class': 'form-control'}),
    }

class DoctorLoginForm(forms.ModelForm):
  class Meta:
    model = Doctor
    fields = ['username', 'password']
    widgets = [passwordInputWidget]
    widgets = {
      'password': forms.PasswordInput(attrs={'class': 'form-control'}),
    }

class OrganizationRegisterForm(forms.ModelForm):
  class Meta:
    model = Organization
    fields = ['name', 'email','username', 'password', 'Organization_Type']
    widgets = [passwordInputWidget]
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'}),
      'username': forms.TextInput(attrs={'class': 'form-control'}),
      'password': forms.PasswordInput(attrs={'class': 'form-control'}),
      'Organization_Type': forms.TextInput(attrs={'class': 'form-control'}),
    }

class OrganizationLoginForm(forms.ModelForm):
  class Meta:
    model = Organization
    fields = ['username', 'password']
    widgets = [passwordInputWidget]
    widgets = {
      'password': forms.PasswordInput(attrs={'class': 'form-control'}),
    }

Team32_October/src/authApp/views.py
from django.shortcuts import render, redirect
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .models import User
from .models import Doctor
from .models import Organization      
from .forms import RegisterForm, LoginForm, DoctorRegisterForm, DoctorLoginForm, OrganizationRegisterForm, OrganizationLoginForm
from .decorators import user_login_required, doctor_login_required, organization_login_required
import random
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from mysite.settings import EMAIL_HOST_USER
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.hashers import make_password, check_password

razorpay_client = razorpay.Client(auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))

def homepage(request):
    return render(request, 'homepage.html')

@user_login_required
def home(request):
 user = get_user(request)
 return render(request, 'home.html', {'user': user})

def ajax_generate_code(request):
    print(request.GET)
    for x in request.GET:
        if x!='_':
            email = x
            request.session['code'] = random.randint(100000, 999999)
            text_content = "Your Email Verification Code is " + str(request.session['code'])
            msg = EmailMultiAlternatives('Verify Email', text_content, EMAIL_HOST_USER, [email])
            msg.send()
    return HttpResponse("success")

def ajax_doctor_code(request):
    print(request.GET)
    for x in request.GET:
        if x!='_':
            email = x
            request.session['code'] = random.randint(100000, 999999)
            text_content = "Your Email Verification Code is " + str(request.session['code'])
            msg = EmailMultiAlternatives('Verify Email', text_content, EMAIL_HOST_USER, [email])
            msg.send()
    return HttpResponse("success")

def ajax_org_code(request):
    print(request.GET)
    for x in request.GET:
        if x!='_':
            email = x
            request.session['code'] = random.randint(100000, 999999)
            text_content = "Your Email Verification Code is " + str(request.session['code'])
            msg = EmailMultiAlternatives('Verify Email', text_content, EMAIL_HOST_USER, [email])
            msg.send()
    return HttpResponse("success")



def register(request):
    form = RegisterForm()
    success = None
    if request.method=='POST':
        if User.objects.filter(username=request.POST['username']).exists():
            error = "This username is already taken"
            return render(request, 'register.html', {'form': form, 'error': error})
        if User.objects.filter(email=request.POST['email']).exists():
            error = "This email is already taken"
            return render(request, 'register.html', {'form': form, 'error': error})
    
        if (not 'code' in request.POST) or (not 'code' in request.session) or (not request.POST['code']==str(request.session['code'])):
            error = "Invalid Verification Code"
            return render(request, 'register.html', {'form': form, 'error': error})
        form = RegisterForm(request.POST)
        new_user = form.save(commit=False)
        new_user.password = make_password(new_user.password)
        new_user.save()
        success = "New User Created Successfully !"
    return render(request, 'register.html', {'form': form, 'success': success})

def login(request):
 form = LoginForm()
 if request.method=='POST':
  username = request.POST['username']
  password = request.POST['password']
  if User.objects.filter(username=username).exists() and check_password(password, User.objects.get(username=username).password):
   user = User.objects.get(username=username)
   request.session['user_id'] = user.id
   return redirect('authApp:home')
 return render(request, 'login.html', {'form': form})

def get_user(request):
 return User.objects.get(id=request.session['user_id'])

def home(request):
 if 'user_id' in request.session:
  user = get_user(request)
  return render(request, 'home.html', {'user': user})
 else:
  return redirect('authApp:login')

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id'] 
    return redirect('authApp:login')

def payment(request):
    currency = 'INR'
    amount = 50000

    razorpay_order = razorpay_client.order.create(dict(amount=amount, currency=currency, payment_capture='0'))

    razorpay_order_id = razorpay_order['id']
    callback_url = 'paymenthandler/'

    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = settings.RAZOR_KEY_ID
    context['razorpay_amount'] = amount
    context['currency'] = currency
    context['callback_url'] = callback_url
 
    return render(request, 'payment.html', context=context)

@csrf_exempt
def paymenthandler(request):
    if request.method == "POST":
        try:
            razorpay_payment_id = request.POST.get('razorpay_payment_id')
            razorpay_order_id = request.POST.get('razorpay_order_id')
            razorpay_signature = request.POST.get('razorpay_signature')
            params_dict = {
                'razorpay_order_id': razorpay_order_id,
                'razorpay_payment_id': razorpay_payment_id,
                'razorpay_signature': razorpay_signature
            }
            
            result = razorpay_client.utility.verify_payment_signature(params_dict)
            if result is not None:
                amount = 50000
                try:
                    razorpay_client.payment.capture(razorpay_payment_id, amount)
                    return render(request, 'paymentsuccess.html')
                except:
                    return render(request, 'paymentfailure.html')
            else:
                return render(request, 'paymentfailure.html')

        except:
            return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()

#create function for doctorregister
def doctorregister(request):
    form = DoctorRegisterForm()
    success = None
    if request.method=='POST':
        if Doctor.objects.filter(username=request.POST['username']).exists():
            error = "This username is already taken"
            return render(request, 'doctorregister.html', {'form': form, 'error': error})
        if Doctor.objects.filter(email=request.POST['email']).exists():
            error = "This email is already taken"
            return render(request, 'doctorregister.html', {'form': form, 'error': error})
    
        if (not 'code' in request.POST) or (not 'code' in request.session) or (not request.POST['code']==str(request.session['code'])):
            error = "Invalid Verification Code"
            return render(request, 'doctorregister.html', {'form': form, 'error': error})
        form = DoctorRegisterForm(request.POST)
        new_user = form.save(commit=False)
        new_user.password = make_password(new_user.password)
        new_user.save()
        success = "Application Submitted Successfully !"
    return render(request, 'doctorregister.html', {'form': form, 'success': success})

def getDoctor(request):
    return Doctor.objects.get(id=request.session['doctor_id'])


#doctor login
def doctorlogin(request):
 form = DoctorLoginForm()
 if request.method=='POST':
  username = request.POST['username']
  password = request.POST['password']
  is_logged_in = True
  if Doctor.objects.filter(username=username).exists() and check_password(password, Doctor.objects.get(username=username).password):
   doctor = Doctor.objects.get(username=username)
   request.session['doctor_id'] = doctor.id
   if is_logged_in:
    return redirect('authApp:doctorhomepage')
   else:
    return redirect('authApp:waiting')
 return render(request, 'doctor_login.html', {'form': form})

@doctor_login_required
def doctorhome(request):
    is_logged_in = Doctor.objects.get(id=request.session['doctor_id']).is_logged_in
    if is_logged_in == True:
        doctor = getDoctor(request)
        return render(request, 'doctor_home.html', {'doctor': doctor})
    else:
        return redirect('authApp:waiting')

def doctorlogout(request):
    if 'doctor_id' in request.session:
        del request.session['doctor_id'] 
    return redirect('authApp:doctorlogin')

def landing_page(request):
    return render(request, 'landing_page.html')

def waiting(request):
    return render(request, 'waiting.html')

def organization_register(request):
    form = OrganizationRegisterForm()
    success = None
    if request.method=='POST':
        if Organization.objects.filter(username=request.POST['username']).exists():
            error = "This username is already taken"
            return render(request, 'organization_register.html', {'form': form, 'error': error})
        if Organization.objects.filter(email=request.POST['email']).exists():
            error = "This email is already taken"
            return render(request, 'organization_register.html', {'form': form, 'error': error})
    
        if (not 'code' in request.POST) or (not 'code' in request.session) or (not request.POST['code']==str(request.session['code'])):
            error = "Invalid Verification Code"
            return render(request, 'organization_register.html', {'form': form, 'error': error})
        form = OrganizationRegisterForm(request.POST)
        new_user = form.save(commit=False)
        new_user.password = make_password(new_user.password)
        new_user.save()
        success = "Application Submitted Successfully !"
    return render(request, 'organization_register.html', {'form': form, 'success': success})

def getOrganization(request):
    return Organization.objects.get(id=request.session['organization_id'])

def organization_login(request):
 form = OrganizationLoginForm()
 if request.method=='POST':
  username = request.POST['username']
  password = request.POST['password']

Team32_October/src/authApp/templates/doctor_home.html
<div>
    Welcome {{ doctor.username }}
    <p> Name : {{ doctor.name }} </p>
    <p> Username : {{ doctor.username }} </p>
    <p> Email : {{ doctor.email }} </p>
    <p> Department : {{ doctor.department }}</p>
   </div>
   <div>To logout, <a href="{% url 'authApp:doctorlogout' %}">Click Here</a></div>

Team32_October/src/authApp/templates/doctor_login.html
<html>
<head>
<title>Tiger Healthcare</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="banner">
        <div class="logo"><img src="/templates/logo.png" width="200" height="100" alt="logo"></div>
        <div class="banner_text">
            <h1>Tiger Healthcare</h1>
        </div>
    </div>

    <div class = "bod">
        <h2>Welcome Back Doctor!</h2>
    </div>

<form method="post" autocomplete="off">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Login</button>
    <div>Don't have an account? <a href="{% url 'authApp:register' %}">Sign up</a>
</form>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>

</html>

Team32_October/src/authApp/templates/doctorregister.html
<html>
    <body onunload=''>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% if success %}
<div> {{ success }} </div>
{% endif %}
{% if error %}
<div> {{ error }} </div>
{% endif %}
<form method="post" autocomplete="off">
 {% csrf_token %}
 {{ form.as_p }}
 <input type='number' name='code' id='id_code' placeholder="Enter Verification Code.." style="display: none;">
 <button id='regBtn'>Register</button>
 <div>Already have an account? <a href="{% url 'authApp:login' %}">Sign in</a>
</form>
<script>
 $('#regBtn').on('click', function(e){
  if($("#id_code").css('display')=='none'){
   e.preventDefault();
   var dataToGo = $('#id_email').val();
   console.log(dataToGo);
   $.ajax({
           url: "{% url 'authApp:ajax_generate_code' %}",
           type: 'GET',
           data: dataToGo,
           success: function (data) {
               $('#id_code').css('display', 'block');
           },
           cache: false,
           contentType: false,
           processData: false
        });
  }
 })
</script>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>
</html>

Team32_October/src/authApp/templates/home.html
<div>
    Welcome {{ user.username }}
    <p> Name : {{ user.name }} </p>
    <p> Username : {{ user.username }} </p>
    <p> Email : {{ user.email }} </p>
    <p> Blood : {{ user.blood }}</p>
   </div>
   <div>To upload documents, click <a href="/file">here</a></div>
   <div>To upload documents(fr), click <a href="/myapp">here</a></div>
   <div>To pay for your medical bills, click <a href="{% url 'authApp:payment' %}">here</a></div>
   <div>To logout, <a href="{% url 'authApp:logout' %}">Click Here</a></div>

Team32_October/src/authApp/templates/homepage.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class="nav-container">
            <div class="wrapper">
                <nav>
                    <div class = "logo">
                        <a href = "index.html"><img src = "logo.png" alt = "logo"></a>
                    </div>
                    <ul class="nav-items">
                        <li><a href = "login.html">Log In</a></li>
                        <li><a href = "register.html">Sign Up</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        
        <script src="" async defer></script>
    </body>
</html>

Team32_October/src/authApp/templates/landing_page.html
<div>Admin Login<a href="admin/">Click Here</a></div>
<div>Doctor Login<a href="{% url 'authApp:doctorlogin' %}">Click Here</a></div>
<div>User Login<a href="{% url 'authApp:login' %}">Click Here</a></div>
<div>Organization Login<a href="{% url 'authApp:organizationlogin' %}">Click Here</a></div>

Team32_October/src/authApp/templates/login.html
<html>
<head>
<title>Tiger Healthcare</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="banner">
        <div class="logo"><img src="/templates/logo.png" width="200" height="100" alt="logo"></div>
        <div class="banner_text">
            <h1>Tiger Healthcare</h1>
        </div>
    </div>

    <div class = "bod">
        <h2>Welcome Back Customer!</h2>
    </div>

<form method="post" autocomplete="off">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Login</button>
    <div>Don't have an account? <a href="{% url 'authApp:register' %}">Sign up</a>
</form>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>

</html>

Team32_October/src/authApp/templates/organization_home.html
<div>
    Welcome {{ organization.username }}
    <p> Name : {{ organization.name }} </p>
    <p> Username : {{ organization.username }} </p>
    <p> Email : {{ organization.email }} </p>
    <p> Department : {{ organization.Organization_Type }}</p>
   </div>
   <div>To logout, <a href="{% url 'authApp:organizationlogout' %}">Click Here</a></div>

Team32_October/src/authApp/templates/organization_login.html
<html>
<head>
<title>Tiger Healthcare</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="banner">
        <div class="logo"><img src="/templates/logo.png" width="200" height="100" alt="logo"></div>
        <div class="banner_text">
            <h1>Tiger Healthcare</h1>
        </div>
    </div>

    <div class = "bod">
        <h2>Welcome Back!</h2>
    </div>

<form method="post" autocomplete="off">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Login</button>
    <div>Don't have an account? <a href="{% url 'authApp:organizationregister' %}">Sign up</a>
</form>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>

</html>

Team32_October/src/authApp/templates/organization_register.html
<html>
    <body onunload=''>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% if success %}
<div> {{ success }} </div>
{% endif %}
{% if error %}
<div> {{ error }} </div>
{% endif %}
<form method="post" autocomplete="off">
 {% csrf_token %}
 {{ form.as_p }}
 <input type='number' name='code' id='id_code' placeholder="Enter Verification Code.." style="display: none;">
 <button id='regBtn'>Register</button>
 <div>Already have an account? <a href="{% url 'authApp:organizationlogin' %}">Sign in</a>
</form>
<script>
 $('#regBtn').on('click', function(e){
  if($("#id_code").css('display')=='none'){
   e.preventDefault();
   var dataToGo = $('#id_email').val();
   console.log(dataToGo);
   $.ajax({
           url: "{% url 'authApp:ajax_organization_code' %}",
           type: 'GET',
           data: dataToGo,
           success: function (data) {
               $('#id_code').css('display', 'block');
           },
           cache: false,
           contentType: false,
           processData: false
        });
  }
 })
</script>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>
</html>

Team32_October/src/authApp/templates/payment.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Payment Gateway</title>
    <style>
         
      * {
        box-sizing: border-box;
        padding: 0px;
        margin: 0px;
      }
      html,
      body {
        height: 100%;
      }
      body {
        background-color: #f1f5f8;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .card {
        background-color: white;
        padding: 25px;
        border: 1px solid #bbbbbb;
        border-radius: 5px;
        box-shadow: 1px 1px 10px 0px rgb(0 0 0 / 25%);
      }
      .title {
        text-align: center;
        letter-spacing: 1px;
      }
      .muted {
        color: #8e7f7f;
        display: block;
        margin-bottom: 10px;
        text-align: center;
      }
      .btn_container {
        padding: 20px;
        text-align: center;
      }
      .btn {
        border-radius: 4px;
        cursor: pointer;
        padding: 4px 8px;
        background-color: #C20E2E;
        color: white;
        font-size: 1.2em;
        font-weight: 600;
        letter-spacing: 1px;
      }
    </style>
  </head>
  <body>
    <div class="card">
      <h1 class="title">Pay for your medical bills</h1>
      <small class="muted"
        >If you live, please pay ₹500</small>
      <div class="btn_container">
        <!-- Payment Button -->
        <button class="btn" id="pay-btn">Pay❤️</button>
      </div>
    </div>
  </body>
   
  <!-- Razorpay's Javascript code. -->
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
    var options = {
       
      // Enter the Key ID generated from the Dashboard
      key: "{{ razorpay_merchant_key }}",
       
      // Amount is in currency subunits.
      // Default currency is INR. Hence,
      // 50000 refers to 50000 paise
      amount: "{{ razorpay_amount }}",
      currency: "{{ currency }}",
       
      // Your/store name.
      name: "Tiger Healthcare",
       
      // Pass the `id` obtained in the response of Step 1
      order_id: "{{ razorpay_order_id }}",
      callback_url: "{{ callback_url }}",
    };
     
    // initialise razorpay with the options.
    var rzp1 = new Razorpay(options);
     
    // add event listener to the payment button.
    document.getElementById("pay-btn").onclick = function (e) {
      rzp1.open();
      e.preventDefault();
    };
  </script>

  <script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</html>

Team32_October/src/authApp/templates/paymentfailure.html
<html>
<head>
<title>Payment Failure</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
<h1>Payment Failure</h1>
</body>
</html>

Team32_October/src/authApp/templates/register.html
<html>
    <body onunload=''>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% if success %}
<div> {{ success }} </div>
{% endif %}
{% if error %}
<div> {{ error }} </div>
{% endif %}
<form method="post" autocomplete="off">
 {% csrf_token %}
 {{ form.as_p }}
 <input type='number' name='code' id='id_code' placeholder="Enter Verification Code.." style="display: none;">
 <button id='regBtn'>Register</button>
 <div>Already have an account? <a href="{% url 'authApp:login' %}">Sign in</a>
</form>
<script>
 $('#regBtn').on('click', function(e){
  if($("#id_code").css('display')=='none'){
   e.preventDefault();
   var dataToGo = $('#id_email').val();
   console.log(dataToGo);
   $.ajax({
           url: "{% url 'authApp:ajax_generate_code' %}",
           type: 'GET',
           data: dataToGo,
           success: function (data) {
               $('#id_code').css('display', 'block');
           },
           cache: false,
           contentType: false,
           processData: false
        });
  }
 })
</script>

<script>
    //script to protect against DDoS attacks
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</body>
</html>

Team32_October/src/authApp/templates/waiting.html
wait for Verification