Team32_October/src/authApp/urls.py
from django.urls import include, path
from . import views
from django.urls import path, include 

app_name = 'authApp'
urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('', views.landing_page, name='landing_page'),
    path('logout/', views.logout, name='logout'),
    path('ajax_generate_code/', views.ajax_generate_code, name='ajax_generate_code'),
    path("file/", include("fileupload.urls")),
    path('payment/paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('payment/', views.payment, name='payment'),
    path('doctorregistration/', views.doctorregister, name='doctorregistration'),
    path('doctorlogin/', views.doctorlogin, name='doctorlogin'),
    path('doctorlogout/', views.doctorlogout, name='doctorlogout'),
    path('doctorhomepage/', views.doctorhome, name='doctorhomepage'),
    path('waiting/', views.waiting, name='waiting'),
    path('ajax_doctor_code/', views.ajax_doctor_code, name='ajax_doctor_code'),
    path('ajax_org_code/', views.ajax_org_code, name='ajax_organization_code'),
    path('organizationregister/', views.organization_register, name='organizationregister'),
    path('organizationlogin/', views.organization_login, name='organizationlogin'),
    path('organizationlogout/', views.organization_logout, name='organizationlogout'),
    path('organizationhome/', views.organization_home, name='organizationhome'),

]

Team32_October/src/myapp/urls.py
from django.urls import path
from .views import my_view, docsls

urlpatterns = [
    path('', my_view, name='my-view'),
    path('docsls/', docsls, name='docsls'),
]

Team32_October/src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('homepage/', include('authApp.urls')),
    path("admin/", admin.site.urls),
    path("", include("authApp.urls")),
    path("file/", include("fileupload.urls")),
    path("myapp/", include("myapp.urls")),
]

Team32_October/src/myapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
User=get_user_model()
# Create your models here.
class Document(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.SET_NULL)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

Team32_October/src/myapp/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(label='Select a file')

Team32_October/src/myapp/views.py
from django.shortcuts import redirect, render
from .models import Document
from .forms import DocumentForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView
# Create your views here.


def my_view(request):
    print(f"Great! You're using Python 3.6+. If you fail here, use the right version.")
    message = 'Upload as many files as you want!'
    # Handle file upload
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = DocumentForm(request.POST, request.FILES)
            form.user = request.user
            if form.is_valid():
                newdoc = Document(docfile=request.FILES['docfile'])
                newdoc.user = request.user;
                newdoc.save()

                # Redirect to the document list after POST
                return redirect('my-view')
            else:
                message = 'The form is not valid. Fix the following error:'
        else:
            form = DocumentForm()  # An empty, unbound form

    # Load documents for the list page
    if request.user.is_authenticated:
        documents = Document.objects.filter(user=request.user)
        # Render list page with the documents and the form
        context = {'documents': documents, 'form': form, 'message': message}
        return render(request, 'list.html', context)
    else:
        return render(request, 'list.html', {'message': message})


def docsls(request):
    queryset = Document.objects.filter(user=request.user)
    context = {
        'object_list': queryset
    }
    return render(request, 'doclist.html', context)

Team32_October/src/myapp/templates/doclist.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title></title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="">
   </head>
   <body>
      <h1>Docs</h1>

      {% for instance in object_list %}
          <p>{{ instance.id }} - <a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></p>
       {% endfor %}
      
      <script src="" async defer></script>
   </body>
</html>

Team32_October/src/myapp/templates/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
        <a href="#">Hi {{user.username}}</a>
        <!-- List of uploaded documents -->
        {% if documents %}
            All documents in the database:
            <ul>
                {% if user.is_authenticated %}
                    {% for document in documents %}
                        {% if document.user == request.user %}
                            <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "my-view" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ message }}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
        
        <div>To go back home,, <a href="{% url 'authApp:home' %}">Click Here</a></div>
        <div>See docs  <a href="{% url 'docsls' %}">Click Here</a></div>
    </body>
</html>